### ISSUE TITLE
SHA in PR comment?

### ISSUE THREAD

**Issue by tdhock** [FabrizioSandri/RcppDeepState-action#13]
Hey @FabrizioSandri in https://github.com/tdhock/binsegRcpp/pull/13 I noticed that when there is some problem with the yaml file, the RcppDeepState PR comment does not get updated, because the RcppDeepState action does not run. In that case, it would be useful to know which commit was used to generate the PR comment. Does that make sense? If so, could you please add the SHA to the PR comment?

**Comment by tdhock** [comment]
for reference the current PR comment looks like this
## [RcppDeepState](https://github.com/FabrizioSandri/RcppDeepState) Report
|function_name|message|file_line|address_trace|R_code|
|-|-|-|-|-|
|cum_median_interface|40 bytes in 1 blocks are definitely lost in loss record 14 of 1,293|[interface.cpp:11](https://github.com/tdhock/binsegRcpp/blob/check-rcppdeepstate/src/interface.cpp#L11)|No Address Trace found|<details><summary>Test code</summary><pre>testlist <- list(data_vec = c(5.74164654148494e-66, -7.10781162332433e-113, 3.7561400587371e-242, -4.18624601367944e+285, -1.21211432023912e+238, -6.94147686662953e+141, 6.88559521458515e+113, 9.1767187283897e+254, -8.88591251567735e-262, -6.59744957120882e-307, 8.38580644838029e+91, -4.97689152397696e-23, 6.95237523357045e-49, -7.50246492832277e-306, 3.11770124693239e+97, -3.7142678007851e+93, -4.3765347540183e-70, -3.1009642806927e+90, 4.23184977474741e+132, -1.85589640667345e-243, 2.30730297270095e+58, 2.39038129756535e-136, -1.64688281235401e-262, 1.66451571655133e-144, -2.88534867103572e+307, -1.08662629566361e-112, 2.95610825086555e-188, -1.22437966078013e-221, 5.33472247014936e+279, -1.22509239136324e+122, -2.77197012819475e-123, 7.30513577907399e+270, 2.53291027667769e-160, 1.29318530483566e-24, 8.88931836632552e-90, -4.21940793462645e+190, -4.38003444668698e+213, 1.31457953805832e-45, -2.68666904782519e-226, -9.4372002905704e+255, 3.59117822940217e-99, -4.08906301752782e+162, -3.23734588465544e-119, 1.14073538647992e-132, -9.79583874895732e-267, -2.40808212315584e+131, -1.40210876532927e-95, 1.55684657827289e-67, -1227055554310685, 9.13646038428653e-44, 2.46373384256697e+245, 1.08174024809998e+151, 1.20452861709388e-101, -3.44930951737462e-101, 3.56872545016976e-275, -9.1951173862082e+270, 7.91564350667984e-140, -1.06355433355864e-167, -4.04708859308699e+81, -1.4324878087796e+97, -1.30296345307321e-81, 2.27589835521444e-128, -6.55816043846907e+305, -7.88481686387161e+77, -8.03336197243059e-07, 9.19940760823822e-66, 4.86638941596697e-67, 2.16030049305924e-236, -4.31829194712598e+143, -1.31864215592991e+156, -2.99258560259597e-65, 1.66578172813665e-298, 2.82828963556084e+305, 3.57732726729609e-177, 1.93147830021598e-230, -4.93047443251854e-36, 1.44323445287025e+307), weight_vec = c(-4.2577682142529e+140, 8.51015222513603e-169, NaN, NaN, 0))<br/>result <- do.call(binsegRcpp:::cum_median_interface, testlist)</pre></details>|
### Analyzed functions summary
|function_name|tested_inputs|
|-|-|
|binseg_interface|10|
|cum_median_interface|10|
|depth_first_interface|10|

**Comment by FabrizioSandri** [comment]
@tdhock You're right; this makes perfect sense.
Because the pull request code can change over time, it is preferable to refer to the commit SHA rather than the entire pull request inside hyperlinks. I'll add this new feature and also add the SHA you mentioned in the first comment. I'll open a new pull request for these changes.

**Comment by FabrizioSandri** [comment]
@tdhock With pull request #15, I added these new features. Furthermore, as you suggested during the meeting, I added an `error` column to the summary table so that the user can see how many tests failed. Let me know if anything needs to be changed, otherwise I will merge pull request #15.
