### ISSUE TITLE
Not finding source files from DESCRIPTION `LinkingTo:` field?

### ISSUE THREAD

**Issue by ms609** [FabrizioSandri/RcppDeepState-action#19]
Run: [FabrizioSandri/RcppDeepState-actionhttps://github.com/ms609/TreeDist/runs/8093288345?check_suite_focus=true](https://github.com/ms609/TreeDist/runs/8093288345?check_suite_focus=true)

Error message:
```
In file included from /github/workspace/src/lap.cpp:27:
/github/workspace/src/tree_distances.h:4:10: fatal error: 'TreeTools/SplitList.h' file not found
#include <TreeTools/SplitList.h>
         ^~~~~~~~~~~~~~~~~~~~~~~
```

the "TreeTools" imports are imported from the TreeTools package, which is linked from the DESCRIPTION's `LinkingTo` field.  My assumption is that this is not being installed as required - but I may be interpreting the log wrongly?

**Comment by FabrizioSandri** [comment]
@ms609 I fixed this problem in pull request https://github.com/FabrizioSandri/RcppDeepState/pull/27. Please let me know if the problem persists.

**Comment by ms609** [comment]
The run has completed successfully, thanks!
