### ISSUE TITLE
what to do when auto comments are too large?

### ISSUE THREAD

**Issue by tdhock** [FabrizioSandri/RcppDeepState-action#5]
@FabrizioSandri this comment https://github.com/FabrizioSandri/RcppDeepState-action/pull/4#issuecomment-1195515527 has 4606 characters (5 functions/rows, 1 argument each) but this https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867/2 says the limit for comment body is about 65k characters (factor of ten larger than this example comment).
maybe try to upload a zip file with data if comment is too large? seems like a theoretical concern (probably won't have a package with tons of functions with problems, and tons of arguments) so let's fix this later.

**Comment by FabrizioSandri** [comment]
Hi @tdhock I was wondering if a possible solution for this problem is to truncate the comment in the following way:
if the comment size exceeds the maximum GitHub comment length, truncate the exceeding lines of the table containing the errors and upload an artifact file containing the markdown of the comment.

**Comment by tdhock** [comment]
sounds reasonable.

**Comment by FabrizioSandri** [comment]
>  truncate the Action's comment in the following way:
if the comment size exceeds the maximum GitHub comment length, truncate the exceeding lines of the table containing the errors and upload an artifact file containing the markdown of the comment.
>
> The Summary table at the end of the comment will not be truncated since the truncation of the error table takes precedence.

@tdhock I solved this issue by following the mentioned approach.

Solved with #10
